export const popularCurrencies = [
    { value: "EUR", label: "🇪🇺 EUR €" },
    { value: "USD", label: "🇺🇸 USD $" },
    { value: "GBP", label: "🇬🇧 GBP £" },
    { value: "JPY", label: "🇯🇵 JPY ¥" },
    { value: "CHF", label: "🇨🇭 CHF CHF" },
    { value: "CAD", label: "🇨🇦 CAD C$" },
    { value: "AUD", label: "🇦🇺 AUD A$" },
    { value: "CNY", label: "🇨🇳 CNY ¥" },
    { value: "SEK", label: "🇸🇪 SEK kr" },
    { value: "NOK", label: "🇳🇴 NOK kr" },
    { value: "DKK", label: "🇩🇰 DKK kr" },
    { value: "PLN", label: "🇵🇱 PLN zł" },
    { value: "CZK", label: "🇨🇿 CZK Kč" },
    { value: "HUF", label: "🇭🇺 HUF Ft" },
    { value: "RON", label: "🇷🇴 RON L" },
    { value: "BGN", label: "🇧🇬 BGN лв" },
    { value: "TRY", label: "🇹🇷 TRY ₺" },
    { value: "INR", label: "🇮🇳 INR ₹" },
    { value: "BRL", label: "🇧🇷 BRL R$" },
    { value: "MXN", label: "🇲🇽 MXN $" },
    { value: "KRW", label: "🇰🇷 KRW ₩" },
    { value: "SGD", label: "🇸🇬 SGD S$" },
    { value: "HKD", label: "🇭🇰 HKD HK$" },
    { value: "NZD", label: "🇳🇿 NZD NZ$" },
    { value: "ZAR", label: "🇿🇦 ZAR R" }
];

export const otherCurrencies = [
    { value: "AED", label: "🇦🇪 AED د.إ" },
    { value: "AFN", label: "🇦🇫 AFN ؋" },
    { value: "ALL", label: "🇦🇱 ALL L" },
    { value: "AMD", label: "🇦🇲 AMD ֏" },
    { value: "ANG", label: "🇨🇼 ANG ƒ" },
    { value: "AOA", label: "🇦🇴 AOA Kz" },
    { value: "ARS", label: "🇦🇷 ARS $" },
    { value: "AWG", label: "🇦🇼 AWG ƒ" },
    { value: "AZN", label: "🇦🇿 AZN ₼" },
    { value: "BAM", label: "🇧🇦 BAM KM" },
    { value: "BBD", label: "🇧🇧 BBD Bds$" },
    { value: "BDT", label: "🇧🇩 BDT ৳" },
    { value: "BHD", label: "🇧🇭 BHD .د.ب" },
    { value: "BIF", label: "🇧🇮 BIF FBu" },
    { value: "BMD", label: "🇧🇲 BMD BD$" },
    { value: "BND", label: "🇧🇳 BND B$" },
    { value: "BOB", label: "🇧🇴 BOB Bs." },
    { value: "BSD", label: "🇧🇸 BSD B$" },
    { value: "BTN", label: "🇧🇹 BTN Nu." },
    { value: "BWP", label: "🇧🇼 BWP P" },
    { value: "BYN", label: "🇧🇾 BYN Br" },
    { value: "BZD", label: "🇧🇿 BZD BZ$" },
    { value: "CDF", label: "🇨🇩 CDF FC" },
    { value: "CLP", label: "🇨🇱 CLP $" },
    { value: "CNH", label: "🇨🇳 CNH ¥" },
    { value: "COP", label: "🇨🇴 COP $" },
    { value: "CRC", label: "🇨🇷 CRC ₡" },
    { value: "CUP", label: "🇨🇺 CUP $" },
    { value: "CVE", label: "🇨🇻 CVE $" },
    { value: "DJF", label: "🇩🇯 DJF Fdj" },
    { value: "DOP", label: "🇩🇴 DOP RD$" },
    { value: "DZD", label: "🇩🇿 DZD د.ج" },
    { value: "EGP", label: "🇪🇬 EGP E£" },
    { value: "ERN", label: "🇪🇷 ERN Nfk" },
    { value: "ETB", label: "🇪🇹 ETB Br" },
    { value: "FJD", label: "🇫🇯 FJD FJ$" },
    { value: "FKP", label: "🇫🇰 FKP £" },
    { value: "GEL", label: "🇬🇪 GEL ₾" },
    { value: "GGP", label: "🇬🇬 GGP £" },
    { value: "GHS", label: "🇬🇭 GHS GH₵" },
    { value: "GIP", label: "🇬🇮 GIP £" },
    { value: "GMD", label: "🇬🇲 GMD D" },
    { value: "GNF", label: "🇬🇳 GNF FG" },
    { value: "GTQ", label: "🇬🇹 GTQ Q" },
    { value: "GYD", label: "🇬🇾 GYD G$" },
    { value: "HNL", label: "🇭🇳 HNL L" },
    { value: "HTG", label: "🇭🇹 HTG G" },
    { value: "IDR", label: "🇮🇩 IDR Rp" },
    { value: "ILS", label: "🇮🇱 ILS ₪" },
    { value: "IQD", label: "🇮🇶 IQD ع.د" },
    { value: "IRR", label: "🇮🇷 IRR ﷼" },
    { value: "ISK", label: "🇮🇸 ISK kr" },
    { value: "JEP", label: "🇯🇪 JEP £" },
    { value: "JMD", label: "🇯🇲 JMD J$" },
    { value: "JOD", label: "🇯🇴 JOD د.ا" },
    { value: "KES", label: "🇰🇪 KES KSh" },
    { value: "KGS", label: "🇰🇬 KGS сом" },
    { value: "KHR", label: "🇰🇭 KHR ៛" },
    { value: "KMF", label: "🇰🇲 KMF CF" },
    { value: "KPW", label: "🇰🇵 KPW ₩" },
    { value: "KWD", label: "🇰🇼 KWD د.ك" },
    { value: "KYD", label: "🇰🇾 KYD CI$" },
    { value: "KZT", label: "🇰🇿 KZT ₸" },
    { value: "LAK", label: "🇱🇦 LAK ₭" },
    { value: "LBP", label: "🇱🇧 LBP ل.ل" },
    { value: "LKR", label: "🇱🇰 LKR Rs" },
    { value: "LRD", label: "🇱🇷 LRD L$" },
    { value: "LSL", label: "🇱🇸 LSL L" },
    { value: "LYD", label: "🇱🇾 LYD ل.د" },
    { value: "MAD", label: "🇲🇦 MAD د.م." },
    { value: "MDL", label: "🇲🇩 MDL L" },
    { value: "MGA", label: "🇲🇬 MGA Ar" },
    { value: "MKD", label: "🇲🇰 MKD ден" },
    { value: "MMK", label: "🇲🇲 MMK K" },
    { value: "MNT", label: "🇲🇳 MNT ₮" },
    { value: "MOP", label: "🇲🇴 MOP MOP$" },
    { value: "MRU", label: "🇲🇷 MRU UM" },
    { value: "MUR", label: "🇲🇺 MUR ₨" },
    { value: "MVR", label: "🇲🇻 MVR ރ." },
    { value: "MWK", label: "🇲🇼 MWK MK" },
    { value: "MYR", label: "🇲🇾 MYR RM" },
    { value: "MZN", label: "🇲🇿 MZN MT" },
    { value: "NAD", label: "🇳🇦 NAD N$" },
    { value: "NGN", label: "🇳🇬 NGN ₦" },
    { value: "NIO", label: "🇳🇮 NIO C$" },
    { value: "NPR", label: "🇳🇵 NPR ₨" },
    { value: "OMR", label: "🇴🇲 OMR ر.ع." },
    { value: "PAB", label: "🇵🇦 PAB B/." },
    { value: "PEN", label: "🇵🇪 PEN S/" },
    { value: "PGK", label: "🇵🇬 PGK K" },
    { value: "PHP", label: "🇵🇭 PHP ₱" },
    { value: "PKR", label: "🇵🇰 PKR ₨" },
    { value: "PYG", label: "🇵🇾 PYG ₲" },
    { value: "QAR", label: "🇶🇦 QAR ر.ق" },
    { value: "RSD", label: "🇷🇸 RSD дин." },
    { value: "RUB", label: "🇷🇺 RUB ₽" },
    { value: "RWF", label: "🇷🇼 RWF FRw" },
    { value: "SAR", label: "🇸🇦 SAR ر.س" },
    { value: "SBD", label: "🇸🇧 SBD SI$" },
    { value: "SCR", label: "🇸🇨 SCR ₨" },
    { value: "SDG", label: "🇸🇩 SDG ج.س." },
    { value: "SHP", label: "🇸🇭 SHP £" },
    { value: "SLE", label: "🇸🇱 SLE Le" },
    { value: "SOS", label: "🇸🇴 SOS Sh" },
    { value: "SRD", label: "🇸🇷 SRD SRD$" },
    { value: "SSP", label: "🇸🇸 SSP £" },
    { value: "STN", label: "🇸🇹 STN Db" },
    { value: "SVC", label: "🇸🇻 SVC $" },
    { value: "SYP", label: "🇸🇾 SYP £" },
    { value: "SZL", label: "🇸🇿 SZL E" },
    { value: "THB", label: "🇹🇭 THB ฿" },
    { value: "TJS", label: "🇹🇯 TJS ЅМ" },
    { value: "TMT", label: "🇹🇲 TMT m" },
    { value: "TND", label: "🇹🇳 TND د.ت" },
    { value: "TOP", label: "🇹🇴 TOP T$" },
    { value: "TTD", label: "🇹🇹 TTD TT$" },
    { value: "TWD", label: "🇹🇼 TWD NT$" },
    { value: "TZS", label: "🇹🇿 TZS Sh" },
    { value: "UAH", label: "🇺🇦 UAH ₴" },
    { value: "UGX", label: "🇺🇬 UGX USh" },
    { value: "UYU", label: "🇺🇾 UYU $U" },
    { value: "UZS", label: "🇺🇿 UZS so'm" },
    { value: "VES", label: "🇻🇪 VES Bs." },
    { value: "VND", label: "🇻🇳 VND ₫" },
    { value: "VUV", label: "🇻🇺 VUV VT" },
    { value: "WST", label: "🇼🇸 WST WS$" },
    { value: "YER", label: "🇾🇪 YER ﷼" },
    { value: "ZMW", label: "🇿🇲 ZMW ZK" },
    { value: "ZWG", label: "🇿🇼 ZWG ZiG" }
];

export const specialCurrencies = [
    { value: "XAF", label: "🌍 XAF" },
    { value: "XAG", label: "🥈 XAG" },
    { value: "XAU", label: "🥇 XAU" },
    { value: "XCD", label: "🌴 XCD" },
    { value: "XCG", label: "🌴 XCG" },
    { value: "XDR", label: "🏦 XDR" },
    { value: "XOF", label: "🌍 XOF" },
    { value: "XPD", label: "⚪ XPD" },
    { value: "XPF", label: "🏝️ XPF" },
    { value: "XPT", label: "⚙️ XPT" }
];